create database company;
use company;
create table EMPL(ID INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(50),AGE INT,SALARY INT);
INSERT INTO EMPL(NAME,AGE,SALARY) VALUES('ARAVITH',30,15000),('ARUN',25,20000);
SELECT*FROM EMPL;
CREATE TABLE DEPARTMENT(DEPT_ID INT AUTO_INCREMENT PRIMARY KEY,DEPT_NAME VARCHAR(50));
INSERT INTO DEPARTMENT (DEPT_NAME)VALUES('MANAGAR'),('HR'),('EMPLOYEE');
SELECT*FROM DEPARTMENT;
CREATE TABLE EMP(EMP_ID INT AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(50),DEPT_ID INT,FOREIGN KEY (DEPT_ID)REFERENCES DEPARTMENT(DEPT_ID));
INSERT INTO EMP(NAME,DEPT_ID)VALUES('PAVI',1),('KAVI',2),('RAVI',3);
SELECT*FROM EMP;
SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
FROM EMP E
INNER JOIN DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID;
SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
FROM EMP E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID
ORDER BY E.EMP_ID;
SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
FROM EMP E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID
ORDER BY E.EMP_ID;
SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
FROM EMP E
CROSS JOIN DEPARTMENT D;
SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
FROM EMP E
LEFT JOIN DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID
UNION
SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
FROM EMP E
RIGHT JOIN DEPARTMENT D
ON E.DEPT_ID=D.DEPT_ID;
SELECT E.EMP_ID,E.NAME,E.DEPT_ID,D.DEPT_NAME
FROM EMP E
JOIN DEPARTMENT D;

